#@TYPE: Machine
#@NAME: Orange Pi 5
#@DESCRIPTION: Orange Pi 5 with Rockchip RK3588S
#http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5.html

require conf/machine/include/rk3588s.inc

KERNEL_DEVICETREE = "rockchip/rk3588s-orangepi-5.dtb"
MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"

UBOOT_MACHINE = "orangepi-5-rk3588s_defconfig"
